### ISSUE TITLE
Input text field cursor position wrong

### ISSUE THREAD

**Issue by weykon** [cooder-org/json-translator#1]
![image](https://github.com/cooder-org/json-translator/assets/36456814/adfd2a1c-8156-4342-a85d-80a32df9554d)

This image shows that his cursor is not properly aligned with the text

**Recurrent**
This problem may occur when the height of the entered text exceeds the existing height of the current view.

I'll try to fix it myself later and give you a PR

**Comment by yanxiyue** [comment]
I appreciate your observation. Your understanding of the issue and your willingness to contribute a fix is commendable. Looking forward to your pull request

**Comment by weykon** [comment]
#2 PR here ! 
the second issue about node version seems you have fixed, so maybe you should process some code merge.
at this issue, I've given it a quick test and fixed the issue. Everything seems to be working fine now.
